### ISSUE TITLE
OData inlinecount adds extra "results" array to "d" AND every expansion.

### ISSUE THREAD

**Issue by crudbetter** [egil/ODataJS#1]
This is an issue with OData itself rather than the ODataJS library.  However it would be nice if ODataJS returns a consistent result object regardless of whether or not an inlinecount has been specified.  I'm currently working on a fix external to JQuery.OData which I should be able to easily port into ODataJS when complete.

**Comment by egil** [comment]
I agree, it should provide the same result object no matter the query type.
